### ISSUE TITLE
[1/12]Go to police for new guy "Yamazaki"

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#107]
residence

**Comment by writerityelena** [comment]
@writerity-watanabe 
can i do this task?

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes. but its Saturday 1/12

**Comment by writerityelena** [comment]
@writerity-watanabe 
i can go anyway if you allow

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks
plz check what document is needed for that

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok! :D
