### ISSUE TITLE
Manage paid holidays for each employee

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#126]
https://docs.google.com/spreadsheets/d/13vUvGZHR76M0Jag5CVRuA6WvJasmNg7pXW6ikAmAfkE/edit?ts=5a5dfc95#gid=1686763465

**Comment by writerityelena** [comment]
Check japanese holidays and macedonian holidays, paid days  for each employee

**Comment by writerityelena** [comment]
21 paid holiday (depends on staff)
---
8 days = follow JP holidays
13days = staff can choose

**Comment by writerity-watanabe** [comment]
@writerityelena 
"depends on staff" means some people have 22, 23 or more holiday based on working experience
"8days" is fixed even if he has 25 paid holidays

**Comment by writerityelena** [comment]
@writerity-watanabe  which one is correct?

1) 2018/03/21  春分の日
2) 2018/07/16  海の日
3) 2018/08/11  山の日
4) 2018/08/27  "National heroes Day
非稼動日"
5) 2018/09/17 "敬老の日
6) 2018/09/23 秋分の日
7) 2018/09/24 振替休日
8) 2018/10/08 体育の日
9) 2018/11/03 文化の日
10) 2018/11/23 勤労感謝の日
11) 2018/12/24 振替休日

**Comment by writerity-watanabe** [comment]
@writerityelena 
you mean, you want to know fo which JP holiday our staff used paid holidays?

**Comment by writerityelena** [comment]
@writerity-watanabe 
Japanese holiday in General

**Comment by writerity-watanabe** [comment]
@writerityelena 
this yellow one is all japanese holiday
![holiday google](https://user-images.githubusercontent.com/36668646/50292613-dbfb3600-0471-11e9-8e32-f66ee27e3b13.jpg)

**Comment by writerityelena** [comment]
@writerity-watanabe 
10x
