### ISSUE TITLE
Utility fee for Company 

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#129]

**Comment by writerityelena** [comment]
@writerity-watanabe 
i will do registration in Municipality of Skopje site because until now we didn't receive utility fee for company 
just tell me what email should i put?

**Comment by writerity-watanabe** [comment]
@writerityelena 
for what exactly we need?

**Comment by writerityelena** [comment]
@writerity-watanabe 
i should check legal papers that Municipality of Skopje probably sent to the old address i suppose (Seavus) 
and if we don't pay this utility fee for company they can block our Comapny's account

**Comment by writerity-watanabe** [comment]
okay 
then plz use my email @writerity.com

**Comment by writerityelena** [comment]
@writerity-watanabe 
pass: 1u7ft2st06cu64n1rihkr3h3p1
