### ISSUE TITLE
Send money to JP company

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#155]
now I am asking company in Japan
- if the price is correct (the will confirm tomorrow hopefully)
- information required to send (bank account, etc)
- send invoice to us

---
https://trello.com/c/9nCMx1Ns/350-%E6%99%82%E5%B7%9D%E7%B5%8C%E8%B2%BB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

---
check list
- [x] registry certificate
- [x] contract with Ones To Watch, Inc.

**Comment by writerity-watanabe** [comment]
@writerityelena 
I hope we finish sending some money to japan tomorrow
cuz its the last day i'm here in this year

if i need to sign sth, can i sign it in advance then even after i go to Japan, you can proceed it probably?


it will be around 2,200,000 den or sth

**Comment by writerityelena** [comment]
@writerity-watanabe 
okay 
what is that ?

**Comment by writerityelena** [comment]
@writerity-watanabe invoice?

**Comment by writerity-watanabe** [comment]
@writerityelena 
this is about Toki's expenses basically that we have to send money back to JP company

**Comment by writerity-watanabe** [comment]
@writerityelena 
JP company will send us invoice
and we pay to them

**Comment by writerityelena** [comment]
@writerity-watanabe 
okay i will also check with accountant tomorrow just make list 
1) this 
2)this etc. 
possible?

**Comment by writerity-watanabe** [comment]
@writerityelena 
already talked here.
![managers about taxed expenses trello](https://user-images.githubusercontent.com/36668646/50296847-a6f3e100-047b-11e9-8c17-1e6387d85e3b.jpg)

https://trello.com/c/wjE035Vq/285-%E7%B5%8C%E8%B2%BB%E3%81%A8%E3%81%97%E3%81%A6%E8%AA%8D%E3%82%81%E3%82%89%E3%82%8C%E3%81%AA%E3%81%84%E3%82%82%E3%81%AE%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6about-taxed-expenses

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes invoice

**Comment by writerity-watanabe** [comment]
@writerityelena 
I know it has to be invoice
but
what i want to know is i need to sign sth or not
and it has to be done bofore i go to japan

**Comment by writerity-watanabe** [comment]
@writerityelena 
today this is the most important task 
thanks

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes ok

**Comment by writerityelena** [comment]
@writerity-watanabe 
-info from japanese company  (must be translated from translator)
- with this document we make request Public office revenue (thus might take 10 days) 
-contract for collaboration between Writerity and JP company (suggested) 
-must be in euros 
-Invoice for services

**Comment by writerity-watanabe** [comment]
@writerityelena 
> -info from japanese company (must be translated from translator)

what kind of info?
need certificate of registry or sth? (copy or original)

> -contract for collaboration between Writerity and JP company (suggested)
Owner is Toki for both company.

> -must be in euros
-Invoice for services

okay

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes certificate from registry form Japan

**Comment by writerity-watanabe** [comment]
@writerityelena 
btw invoice can be in Japanese? or should be English

**Comment by writerityelena** [comment]
@writerity-watanabe 
englsih 
and reason for transfering money

**Comment by writerity-watanabe** [comment]
@writerityyuko 
> yes certificate from registry form Japan

ワンズの登記簿（英語）、別件で折田さんから送付済みでしたか？

**Comment by writerity-watanabe** [comment]
ok
> and reason for transfering money ( i need to check the reason with accountant)

Toki is helping us to run business and find client for Writerity, Inc
and he uses money of JP company for that.

**Comment by writerityelena** [comment]
@writerity-watanabe 
what does japanese company in japan ?
computer services?

**Comment by writerity-watanabe** [comment]
@writerityelena 
its totally different services (model)
but they also helping us to find Japanese company that can work with us (design, system development) and find Japanese people who can come to work (as a manager) here
cuz its easier to do that in japan, not from Skopje

**Comment by writerityelena** [comment]
@writerity-watanabe 
accountant said that the reason why we transfer money is very important, and because there are two comapnies that provide different services (modeling vc computer services) 
If we put reason: business mediation that must have Contract for concluded bargain and business colaboration with client

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes i know reason is important 
but need to transfer money somehow
becasue its hard to find Client or Japanese people from here in Skopje, right?
its easier if we can do that in Japan

need advice from them

**Comment by writerityelena** [comment]
@writerity-watanabe 
example
-you go in Japan , conclude Contract betewen you Toki(JP Company) and our Client 
-that contract can be basis for the money we pay to japanese model comapny 
- business  mediation You ->(JP Company)<- Client

**Comment by writerityelena** [comment]
@writerity-watanabe 
the best is to be in Eng 
you can make in Japanese then traslated in english (but that is more complicated)

**Comment by writerityyuko** [comment]
@writerity-watanabe 
お返事が遅れました。

> ワンズの登記簿（英語）、別件で折田さんから送付済みでしたか

別件か、この件か、ちょっと混乱していますが、
折田さんからは英語版のドラフトを頂いてます。（修正を2点ほどお願いして、その後完成版は共有していません。）

https://github.com/timeriver/company-management/issues/55#issuecomment-446884328

この翻訳した登記簿のアポスティーユを折田さんがとるために、
折田さんがワンズの長田さんに委任状を依頼しているというステータスまでは確認していますが、その後はわかりません。

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you check invoice
if this is acceptable or not

this is how it look.
we will change description or sth else needed to change
[Writerity,Inc invoice 1.pdf](https://github.com/timeriver/company-management/files/2702373/Writerity.Inc.invoice.1.pdf)

**Comment by writerityyuko** [comment]
@writerity-watanabe 

よかったですー。
ということで、本件について私がお手伝いできることはもうなさそうですね。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、ありがとうございました！

**Comment by writerityelena** [comment]
@writerity-watanabe 
Invoice in English

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay i will ask them to do that

**Comment by writerity-watanabe** [comment]
@writerityelena 
and plz check this is acceptable - contract
https://docs.google.com/document/d/1CowlzI0kDirAZAf8tiOV915Z-09CqzyOxwrCXYZ7AFM/edit

**Comment by writerityelena** [comment]
@writerity-watanabe 
Deni and Martin will update the contract , we need 
- period of time or recruiting (for how long he has mediate)

**Comment by writerity-watanabe** [comment]
@writerityelena 
its basically one year (every year, we send money to JP)

**Comment by writerityelena** [comment]
@writerity-watanabe 
amount: around 2,200,000 den or sth 
what is exact?

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz exchange JPY 4,616,773 to EUR or MKD

use today's rate

**Comment by writerity-watanabe** [comment]
@writerityelena 
btw they will translate invoice to Japanese
description can be just "Services"?

**Comment by writerityelena** [comment]
yes specific like contract

**Comment by writerity-watanabe** [comment]
okay

**Comment by writerityelena** [comment]
@writerity-watanabe 
contract will be done around 3-4 o'clock and invoice must have same reason as contract

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks
i can sign contract and invoice in Japan and send you copy? or need to be original?

**Comment by writerityelena** [comment]
@writerity-watanabe 
i think copy is ok but keep the original

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then
we will have contract and invoice in English and i will sign those docs and send to you as pdf
then you can make payment without me?

**Comment by writerityelena** [comment]
@writerity-watanabe 
i think you should give me empowerment

**Comment by writerityelena** [comment]
@writerity-watanabe 
no need for empowerment

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes
only contract and invoice

**Comment by writerityelena** [comment]
@writerity-watanabe 
updates are in red color
https://docs.google.com/document/d/1CowlzI0kDirAZAf8tiOV915Z-09CqzyOxwrCXYZ7AFM/edit

**Comment by writerityelena** [comment]
@writerity-watanabe 
now olnly invoice is left 
should i print this contract?

**Comment by writerity-watanabe** [comment]
@writerityelena 
not yet
I have to look the contract better

**Comment by writerityelena** [comment]
@writerity-watanabe 
accountant is checking procedure today

**Comment by writerityelena** [comment]
@writerity-watanabe 
procedure still on hold because employees from that department in Public Office Revenue are on holiday

**Comment by writerityelena** [comment]
@writerity-watanabe  for this i should go to the bank today

**Comment by writerityelena** [comment]
@writerity-watanabe ok
