### ISSUE TITLE
Check documents for Yamazaki

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#158]

**Comment by writerityelena** [comment]
@writerity-watanabe 
If Yamazaki stays more than 3 months in Macedonia to work, the lawyer shall begin procedure for Employment. 
So, from Japan , Yamazaki should bring:
1 certificate of non conviction 
2  Health Certificate 
3 Diploma from University

**Comment by writerity-watanabe** [comment]
＠writerityelena
about health certificatae, we will apply for it here in macedonia like i did
