### ISSUE TITLE
Take Hide and Toki in bank to extend token and give empowerment to Hide

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#160]

**Comment by writerityelena** [comment]
@writerity-watanabe 
what time is the best for you and Toki?

**Comment by writerity-watanabe** [comment]
@writerityelena 
i will ask him

**Comment by writerity-watanabe** [comment]
@writerityelena 
i forgot what is token for
can you tell me again

and what about paypal account for this company?

**Comment by writerityelena** [comment]
@writerity-watanabe 
token was for online payment 
and tomorrow im checking about paypal

**Comment by writerity-watanabe** [comment]
@writerityelena 
today, 2pm 
Toki coming to office

**Comment by writerityelena** [comment]
@writerity-watanabe 
today we go?

**Comment by writerity-watanabe** [comment]
@writerityelena 
ah he cannot come today so it will be on Monday
-> Toki confirmed it

**Comment by writerityelena** [comment]
@writerity-watanabe 
today?

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes Toki said he will come around 11am and then probably we can go or after lunch maybe
