### ISSUE TITLE
check where the envelope(receipts that we sent to Japan) is now

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#184]
I am asking JP company now but no reply about it yet

**Comment by writerityelena** [comment]
@writerity-watanabe 
this says it has arrived in post office in JP i think, now they have to deliver to adress i think 

JP350 | JPKWSH | 12/21/2018, 6:30:18 AM | Pristignata vo Naizmeni!na po{ta(Izlez)
-- | -- | -- | --

**Comment by writerity-watanabe** [comment]
@writerityelena
can u check somehow its already delivered or failed to deliver and where is it

**Comment by writerityelena** [comment]
@writerity-watanabe 
still not delivered?

**Comment by writerity-watanabe** [comment]
@writerityelena
not yet

**Comment by writerityelena** [comment]
@writerity-watanabe 
status still stays same, i will call to check by phone

**Comment by writerity-watanabe** [comment]
@writerityelena @writerity-t-bojan 
maybe postal code was wrong
166 0023→160 0023

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe According to the tracking number the status of the package remains the same from 12/21/2018. I tried to call Central Post Office in Skopje several times but with no results. From Monday me or Elena will go directly into their offices to try and resolve this issue.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
thanks :)

**Comment by writerityelena** [comment]
@writerity-watanabe 
this is the adress 
![posta](https://user-images.githubusercontent.com/42862453/51481960-78786700-1d95-11e9-9230-67c42ebdd544.jpg)

**Comment by writerityelena** [comment]
@writerity-watanabe 
after accountant im going to post office im thinking to ask them to return the package 
can i?

**Comment by writerity-watanabe** [comment]
@writerityelena 
if its just ask, then you cannot just call them?

**Comment by writerityelena** [comment]
@writerity-watanabe 
already checked online, status still same 
that is why i want to ask to return the package

**Comment by writerity-watanabe** [comment]
@writerityelena 
you can call them and ask if possible to return the package
then if they said its possible, you can go?

**Comment by writerityelena** [comment]
@writerity-watanabe  ok then

**Comment by writerityelena** [comment]
@writerity-watanabe 
i made request for returning the package. 
They said approximately 2m , should arrive on this address here
