### ISSUE TITLE
Pay some fee for apartment

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#188]
![2018-12-29 00 08 02](https://user-images.githubusercontent.com/36668646/50519471-71e03200-0afe-11e9-9da0-adf732f41f74.jpg)
![2018-12-29 00 08 25](https://user-images.githubusercontent.com/36668646/50519472-7278c880-0afe-11e9-9ea5-444b17c8e6d2.jpg)

**Comment by writerityelena** [comment]
@writerity-watanabe 
this is not paid?

**Comment by writerity-watanabe** [comment]
@writerityelena 
probably not
because I just got those paper from the post in my apartment on 12/24

**Comment by writerityelena** [comment]
@writerity-watanabe 
i will need those papers :/ 
we can pay probably when u return

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
if done, add label "Done" and close this issue

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe As soon as a get the authorisation from the Bank I will pay the bill for electricity and I will close this issue. The other bill is paid.
