### ISSUE TITLE
Make folder for document better

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#2]
Writerity
- contract
  - designers
    - employment
    -  engagement 
  - developers
    - employment
    -  engagement 
- invoice
- other
- other
- other
...etc

**Comment by writerity-watanabe** [comment]
@writerityelena 
give me folder url plz

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://drive.google.com/drive/folders/1gfvrxv0ktnX1d9a6GP59P8JmfQT3tAuk

**Comment by writerityelena** [comment]
@writerity-watanabe 
can you check folder CONTRACTS/INVOICE | 契約書&請求書 and [sample]Writerity i updated

**Comment by writerity-watanabe** [comment]
@writerityelena 
so you deleted "CONTRACTS/INVOICE | 契約書&請求書" and transferred everything to "[sample]Writerity" and update folder structure?

plz check all the contracts for all the staff (untill now) are in the correct folder

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://drive.google.com/drive/folders/1K94dffluyGfJrfcAxlTIr_7Pffljcixa
and where to put this airplane ?
