### ISSUE TITLE
Contract w/Owner of the house for new office

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#20]
The things which we have agreed with the owner until now is below;
Rest of things are not discussed yet.

[Renting fee] 
Renting fee for Ground floor will be 10 E / m2 total 800 EURO , 1st floor will be 7 E / m2 for you 
total, 800euro+560euro=1,360 euro
One month renting fee for security deposit 
 
[Place] 
Blagoj Davkov 16, 1000, Skopje,  Republic of Macedonia
 
[Basic equipment] 
The following equipment are included in renting fee :
Lights for each floor
W.C. for each floor
Kitchen equipment only on the first floor
Air conditioners for each floor
Heating system for each floor
Parking space
 
[Owner/Signer] 
Verica Gjozeva
FLORES DOO
BEL KAMEN 17 2420 RADOVIS MACEDONIA
TEL: 00389 71 20 5858
MAIL:flores@flores.com.mk

**Comment by writerity-watanabe** [comment]
@writerityelena @writerityyuko 
plz include these condition below in the contract

- [ ] contract term is 2 years and notice period is 3 months before
- [ ] we might use 2 floors as hostel, cafe, or bar...etc
- [ ] the rent fee wont be increased after contract renewal (4 year after 1st contract)

already talked with Verica.
Plz tell Dejan to include.

and now i am talking with Toki, how to devide cost for pellet with Verica.

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ペレットの件ですが、明日エレナに伝えて、オーナーに言うようにできますか？
（英語で伝えられる自信がなく・・・

▼伝えたいこと
ペレット暖房の設備が10年持つと仮定した場合に
10年で割った分の、さらにフロア分のみをこちらが負担
＊2年で退去したときのことを考えると、無駄金を払うことになる？？

もし、設備投資自体がオーナーの負担であれば、
月々の支払いはフロア分のみにできればベストかなと思います。
比率は別途Vericaと話したいとは思っています。

**Comment by writerityyuko** [comment]
@writerityelena 

Hide is asking about cost of heating system to me.

I have heard that they will put the pellet heater in the parking and heat whole house through pipes.
The heater is included initial equipment like as air conditioners and we pay part of cost of pellet which is for our 2 floors.

Could you ask to Verica whether it is correct understanding or not?

**Comment by writerity-watanabe** [comment]
@writerityyuko 
念のため、こちらもお願いします！

- 夏場は使用しないはずなので、月々０円になるのか
- 冬場、使用したとして、大体いくらくらいの範囲で収まるものなのか（予想つけば）

@writerityelena 
plz ask her also about this
- we dont pay anything in summer (because we dont use heater in summer)
- in winter if we use it, does she have any idea of how much it costs per month (approximately)

**Comment by writerityelena** [comment]
@writerity-watanabe 
contract is already sent to Deni 
im asking now about these 2 new questions

**Comment by writerity-watanabe** [comment]
@writerityelena 
modified questions
- we dont have to pay anything in summer (because we dont use heater in summer)
- in winter if we use it, does she have any idea of how much it costs per month? (approximately)

this one you should ask Verica

**Comment by writerityelena** [comment]
@writerity-watanabe 
- we dont pay in summer for heating (only 3 or 4 months when we use the heating we pay) 
-she will check how much is the cost and will give us the calculation and she confirms that this is the most economical heating she has found

**Comment by writerity-watanabe** [comment]
@writerityelena 
thanks.
after she check ,and Deni include everything in the contract and we check the contract is okay, then i will go to sign the contract with Verica

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok!

**Comment by writerity-watanabe** [comment]
@writerityelena 
you asked about it in email, right

**Comment by writerityelena** [comment]
@writerity-watanabe 
viber 
![fefew](https://user-images.githubusercontent.com/42862453/52059862-3c9a8a00-256b-11e9-9013-bbe28c5534b6.png)

**Comment by writerityelena** [comment]
@writerity-watanabe 
so we put in contract : 
-that we pay heating only for heating season 
-and cost? (verica is offline now)

**Comment by writerity-watanabe** [comment]
@writerityelena 
> that we pay heating only for heating season
yes, but tell Deni what we want and he will change sentence

> and cost? (verica is offline now)
yes we cannot say how much exactly but 
I should talk with her and negotiate after she know how much is the cost and calculation.
then we decide how much we pay for that (for example, 30% of total cost)
