### ISSUE TITLE
check if possible to get one pc for designer by 1/21

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#203]
plz check with Dimitar

**Comment by writerity-watanabe** [comment]
@writerityelena 
this is the most important task in 1/9
plz check with Dimitar

and tell me 
then i will ask you to buy it

**Comment by writerityelena** [comment]
@writerity-watanabe 
doing

**Comment by writerityelena** [comment]
@writerity-watanabe 
we have PC + Monitor probably we'll need one more mouse

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes i know we have one more for new designer
we need one more pc + monitor for JP client coming on 1/21

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok doing

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://www.anhoch.com/product/12487/monitor-24-dell-u2412m-ultrasharp-led-ips-1610-full-hd-dvidpvga5xusbblack

**Comment by writerity-watanabe** [comment]
@elena

not like that....
same spec with our designers...everything plz check with Dimitar
He knows what to do

**Comment by writerityelena** [comment]
@writerity-watanabe 
this was given by Dimitar

**Comment by writerity-watanabe** [comment]
@writerityelena
oh this is only monitor right?
we need also pc

**Comment by writerityelena** [comment]
@writerity-watanabe 
sepcs i already have
same as his only monitor we double check if u approve

**Comment by writerity-watanabe** [comment]
@writerityelena
monitor is okay, it doesnt take time to get one anyway
but pc, we have to order and it might take some weeks or days -> we want to know if we can get one by 1/21 or not

**Comment by writerityelena** [comment]
@writerity-watanabe 
okay , im asking today

**Comment by writerityelena** [comment]
@writerity-watanabe 
tomorrow will know

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you ask supplier also for laptop (same as Dimitar's)

**Comment by writerityelena** [comment]
@writerity-watanabe 
I made reservation 
https://www.anhoch.com/product/44752/notebook-msi-gp63-leopard-i7-8750h16gb1tb128gb-ssdgtx1070-8gb156-120hz-3msvrwin10 
with 32 Gb RAM 
We can buy it on Monday

**Comment by writerity-watanabe** [comment]
@writerityelena
plz check spec for the pc with dimitar and tell me final price
then we can buy it.
we decide today.

**Comment by writerityelena** [comment]
@writerity-watanabe 
Laptopc checkd with Dimitar -> approved 
Monitor = ??
Dimitar already asked you but no answer

**Comment by writerity-watanabe** [comment]
@writerityelena
okay
