### ISSUE TITLE
Register Hide for personal Tax

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#217]

**Comment by writerityelena** [comment]
@writerity-watanabe 
I need 
-passport expiring date
-passport number 
to submit online

**Comment by writerity-watanabe** [comment]
@writerityelena
expiring date is Aug 5th 2023
passport number is TK9581615

**Comment by writerityelena** [comment]
@writerity-watanabe 
pls tell me what day we can go to Public office revenue 
if you don't submit you will pay penalty 200eur i think

**Comment by writerity-watanabe** [comment]
@writerityelena 
tomorrow or Thursday if there wont be no appointment with Verica, KL studio, Security Company, or Insurance Company...etc, then we can go if i really need to go

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes pls
