### ISSUE TITLE
Pay rent for office and apartment

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#219]

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan @writerityelena 
if you can, plz pay fee for office/apartment

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I paid the rent for the office on Monday, I paid the bills for office/apartment today.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay thanks

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
plz update sheet (if need, ask Elena)
https://docs.google.com/spreadsheets/d/1QRt6JSpdk0_ulCKDk4ZEjCiNOfMDHMR0nNg_LJ2_rvY/edit?ts=5a53932f#gid=474459662

and
if use business card, then here
https://docs.google.com/spreadsheets/d/1QRt6JSpdk0_ulCKDk4ZEjCiNOfMDHMR0nNg_LJ2_rvY/edit?ts=5a53932f#gid=1573965212

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I don't have access to the spreadsheets.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
give me email plz

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe writerity.bojan.tasevski@gmail.com

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
done
