### ISSUE TITLE
check how fast we can get 2 desks/chairs from same company

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#232]
we might hire 2 or 3 designers this month/next month

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan @writerityelena 
plz check

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe The cost for a chair is 9858MKD and for a desk 8142MKD. They can be in our office in 15 days starting from the day of the order.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
before it was much more cheaper
in that case, probably its not much different even if we ask the architect to buy

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Is it ok if I order them first thing in the morning?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
if done, add label "Done" and close this issue

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I placed the order.
