### ISSUE TITLE
Help Hide to fill out the document for business trip

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#234]
i keep airplane ticket and receipts for hotel

**Comment by writerity-watanabe** [comment]
@writerityelena 
I already gave the boarding pass to you when i gave the document for trip
plz check again

**Comment by writerityelena** [comment]
@writerity-watanabe 
acountant says you gave ticket only , they need hours for the flight 
if you now what time was each flight you can write here

**Comment by writerity-watanabe** [comment]
@writerityelena 
that is must be written in invoice for ticket

**Comment by writerityelena** [comment]
@writerity-watanabe 
this is boarding pass 
*but if you keep the airplane tickets you can bring them to office (not the invoices from internet we have until now)

![viber image 2019-02-07 09 18 57](https://user-images.githubusercontent.com/42862453/52398625-ff2d8380-2ab9-11e9-8bcc-9e1b86188a7e.jpg)

**Comment by writerityelena** [comment]
@writerity-watanabe 
accountant said we cant submit with that online invoice, they need tickets if you have

**Comment by writerityelena** [comment]
@writerity-watanabe 

-Invoice  6651 Yen paid on 13.10.2018 = from company account?
-Invoice 7365 Yen paid on 10.11.2018 = paid with business  card ?
-Invoice 13 6640 Yen paid on 14.11.2018 = paid with private or company money?
-Invoice 10 328 Yen paid on 07.11.2018,  = paid with private or company money?
-Invoice 11 506 Yen paid on  07.11.2018 = paid private or company money?

**Comment by writerity-watanabe** [comment]
@writerityelena 
> Invoice 6651 Yen paid on 13.10.2018 = from company account?

with company business card 
> Invoice 7365 Yen paid on 10.11.2018 = paid with business card ?

with company business card
> Invoice 13 6640 Yen paid on 14.11.2018 = paid with private or company money?

private and I withdraw that from company money
> Invoice 10 328 Yen paid on 07.11.2018, = paid with private or company money?

private
> Invoice 11 506 Yen paid on 07.11.2018 = paid private or company money?

private

**Comment by writerityelena** [comment]
@writerity-watanabe 
we need this highlighted documents so we can complete documents for profit/loss 
[izvod kartica.pdf](https://github.com/timeriver/company-management/files/2851028/izvod.kartica.pdf)

**Comment by writerity-watanabe** [comment]
@writerityelena 
mostly i guess its for client 
I am asking them to give us email or document.
they dont have boarding pass but they have email or printed document

**Comment by writerity-watanabe** [comment]
@writerityelena 
I forwarded some email for missing documents plz check

**Comment by writerityelena** [comment]
@writerity-watanabe 
among the emails that you sent me are tickets for Ayumi, Kaichi and Tagashi, so these expenses are under personal tax 10% and plus 10% income tax as not approved expenses because they are not employed in the company. 
Anyway these are expenses for 2019 so we have time for this.

**Comment by writerity-watanabe** [comment]
@writerityelena 
so you mean all of this wont be calculated in 2018?
in that case, we again send this receipts to JP this year

**Comment by writerityelena** [comment]
@writerity-watanabe 
i gave to accountant all the tickets you have gave me and everything is ok , you had Boarding pass between the tickets , now he has to calculate everything.  👍

**Comment by writerityelena** [comment]
@writerity-watanabe 
we lack Trip.com invoice paid on 11.12.2018, 27928 YEN =  13 408,00 MKD 
do you have that one in mail or sth?

**Comment by writerity-watanabe** [comment]
@writerityelena 
sent it now
[電子領収書 (4).pdf](https://github.com/timeriver/company-management/files/2874592/4.pdf)
[電子領収書 (5).pdf](https://github.com/timeriver/company-management/files/2874593/5.pdf)

**Comment by writerityelena** [comment]
@writerity-watanabe 
invoice should be 27 928 YEN , this one is 16 790

**Comment by writerity-watanabe** [comment]
@writerityelena 
plus this one
[電子領収書 (6).pdf](https://github.com/timeriver/company-management/files/2874981/6.pdf)
