### ISSUE TITLE
Pay salary for Jan also to Kai

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#236]
▼works from 1/15
350 * 3 * 13 = 13,650yen = 6,279mkd
500 * 3 * 13 = 19,500yen = 8,970mkd

Total GROSS = 15,249mkd (this is not final price yet)
deduct 2,928mkd
= 12,321mkd
NET = ??

*1yen = 0.46mkd

---

**Comment by writerityelena** [comment]
@writerity-watanabe 
Pay salary for Nov also to Kai
this means for November? Are you sure?

**Comment by writerityelena** [comment]
@writerity-watanabe 
checking with accountant ,but there will be procedure 
-first open bank account 
-then go to Public Office Revenue to get confirmation number
- if its for December must be engagement contract with

**Comment by writerityelena** [comment]
@writerity-watanabe 
Gross 12 321 
Net 11 089 
Tax 1232

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you check with accountant
GROSS 12, 755mkd
NET = ??

**Comment by writerity-watanabe** [comment]
@writerityelena 
as I said, i will give him money in cash for Jan.

doesnt matter if its minimum or not
