### ISSUE TITLE
research for“ISO 27001”

### ISSUE THREAD

**Issue by writerity-kai** [timeriver/company-management#238]
about ①cost②take time
http://www.cis-cert.com/System-Certification/Overview-ISO-27001-and-ISO-20000.aspx

and, I want you to research another company about ISO-27001.
I want to compare CIS with another company.
No need to research ISO-20000. 
sorry.
deadline until 29jan

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
plz check
https://github.com/timeriver/company-management/issues/238#issue-400682607

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I contacted two companies and I'm waiting to send me an offer with information about cost, time etc.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
btw this task is for Kai 
plz comment to him next time, plz

**Comment by writerity-t-bojan** [comment]
@writerity-kai I got an offer from one company about implementation and certification of ISO 27001.
For both implementation and certification a outside consultant is needed. The time for implementation is 75 days and implementation costs are 1450 Euro without tax. Certificate is valid to up to three years and certification costs may vary depending from the company 1250 - 1650 Euro and supervisor costs 700 - 850 Euro (two supervisor checks in period of two years are mandatory).
About ISO 20000-1 I'm still waiting an offer, also I asked them to translate the offers on English, so I will make a full update as soon as have more information.

**Comment by writerity-t-bojan** [comment]
@writerity-kai About the offer I mentioned above, the company contacted me and informed that they don't have an English version. Can you please tell me if it is ok to give the offer to the offical translator so I can post it here?
Today I received the second offer from another company and I'm attaching the English version.
This offer is only for certification of ISO 27001. I spoke with an outside consultant about the implementation of the standard itself and according to him costs and time needed depends from the fact if we have someone in the company with ICT knowledge who will help them 50/50 in preparing the documents and the process. In that case the cost will be around 2000 Euro and implementation time cca two months.
If they do the implementation process all by themselves without help from inside the company it will take much longer and will cost 5000 - 7000 Euro. 
If we are interested we can set up an appointment to discuss further details.

[6263_Vrajterti_P1_125.pdf](https://github.com/timeriver/company-management/files/2791648/6263_Vrajterti_P1_125.pdf)

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
> Can you please tell me if it is ok to give the offer to the offical translator so I can post it here?

about this, i will tell you.
no official translator needed. plz read it and try to explain here 
if its too many document, plz ask translator and tell us price to translate

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe The first offer is nine pages long, offical translator costs will be cca 2700MKD, so tomorrow I will give Kai short summarized version of the offer.

**Comment by writerity-t-bojan** [comment]
@writerity-kai  1. Offer from Mobes Kvalitet summarized in English.

https://docs.google.com/document/d/15kJgmLgKzoOOKbpEjq61Gh9Q0zzuaqAdWb7qTrC_wDk/edit

2. Offer from SiQ Ljubljana and it is in English.

[Writerity offer.pdf](https://github.com/timeriver/company-management/files/2807740/Writerity.offer.pdf)
