### ISSUE TITLE
send money to france

### ISSUE THREAD

**Issue by writerity-kai** [timeriver/company-management#239]
how much does it cost to send  money to france?

ex) less than 100EUR

**Comment by writerity-kai** [comment]
@writerity-t-bojan @writerityelena 
plz chk until 25jan

**Comment by writerityelena** [comment]
@writerity-kai 
-what is the reason for sending this money? 
-you pay from Company account?

**Comment by writerity-watanabe** [comment]
@writerity-kai @writerityelena 
> -what is the reason for sending this money?

we will have a freelance contract with people living in France
and we ask him to do work for us
> -you pay from Company account?

yes

**Comment by writerity-watanabe** [comment]
@writerityelena @writerity-kai 
now we are asking JP company if its cheaper or more expensive to send from them to France

plz wait for a while

**Comment by writerity-watanabe** [comment]
@writerityelena 
anyway, plz check how much does it cost send money to France.
around 30~50EUR

**Comment by writerity-kai** [comment]
@writerityelena 
How is the task going?
and,How much does it takes CommissionIf I send money to four perple？

**Comment by writerityelena** [comment]
@writerity-watanabe 
this i should check in Bank or westernmoney

**Comment by writerity-watanabe** [comment]
@writerityelena 
you should tell Kai, not to me

**Comment by writerityelena** [comment]
@writerity-watanabe 
lol sry i didnt see

**Comment by writerity-kai** [comment]
It would be helpful if you do so.

**Comment by writerityelena** [comment]
@writerity-kai 
will do 👍

**Comment by writerityelena** [comment]
@writerity-kai 
provision for 30EUR is 1150 MKD

**Comment by writerityelena** [comment]
@writerity-kai 

 MoneyGram

- 0,01-50 eur = provision 6,90 eur
- 50,01-150 eur = provision 13 eur
-150,01-300 eur =provision 15 eur
