### ISSUE TITLE
Submit Hide for personal Tax

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#251]

**Comment by writerityelena** [comment]
@writerity-watanabe 
pls passport expiring date one more time i cant find the card

**Comment by writerity-watanabe** [comment]
@writerityelena 
[ppt for hide.pdf](https://github.com/timeriver/company-management/files/2779681/ppt.for.hide.pdf)

**Comment by writerityelena** [comment]
@writerity-watanabe 
sorry but the system doesnt allow you will have to come with me in preson
