### ISSUE TITLE
Dinner with SAC

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#255]
kafana on this Friday or next Friday
(depends on everyone)
if everyone can join on this Friday, then we will go to dinner together with them

- place (kafana, good one)
- time (after work, we will ask them)

**Comment by writerityelena** [comment]
@writerity-watanabe  good ^.^

**Comment by writerityelena** [comment]
@writerity-watanabe 
staff is okay for this friday except Kire or Jovica would have to stay overtime for 3h for the exam for developers 
i suggest to reschcedule the exam

**Comment by writerity-watanabe** [comment]
@writerityelena
then 
dinner can be next friday

**Comment by writerityelena** [comment]
@writerity-watanabe 
developers said overtime probably would be 3h

**Comment by writerity-watanabe** [comment]
@writerityelena 
what about dinner next friday

**Comment by writerityelena** [comment]
@writerity-watanabe 
then okay :/

**Comment by writerityelena** [comment]
@writerity-watanabe 
i can speak with them to prepare more traditional food if you want

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
