### ISSUE TITLE
Buy equipment for Okuzawa

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#261]

**Comment by writerityelena** [comment]
@writerity-watanabe 
we need 
-mouse 
-headphones
for Okuzawa

**Comment by writerity-watanabe** [comment]
@writerityelena
okay

**Comment by writerityelena** [comment]
@writerity-watanabe 
this?
https://www.anhoch.com/product/44763/mouse-natec-genesis-gaming-xenon-210-3200dpi-usb-wsoftware

**Comment by writerity-watanabe** [comment]
@writerityelena
plz buy same one
850 is too much

**Comment by writerityelena** [comment]
@writerity-watanabe 
i will take comapny card to buy headphones after work  ok?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
