### ISSUE TITLE
Japan Embassy Hearing 大使館からヒアリングの依頼

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/company-management#263]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

実は昨日、日本大使館の参事官の町田さんから電話がありまして、企業訪問して、活動状況などをヒアリングしたいと依頼がありました。

特に何か重要なことを聞き出したいというよりは、大使館としての一般的な企業訪問という感じで、時間を少し取られるというくらいのデメリットなので、（お付き合い上）お受けしたほうが良いと思いますが、いかがでしょうか？

お急ぎではないということです。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

そろそろ、大使館にご連絡したいのですが、上記、いかがでしょうか？

**Comment by writerity-watanabe** [comment]
＠writerityyuko
すみません！見逃していました。
基本的に午後13時以降あれば問題ありません！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

承知しました。それでは来週の30日（水）13:00か、1日（金）の13:00で、打診してみます。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
町田さんからのメール確認しました。
来週も、13時以降なら問題ないです！
午前の方が良ければ、木・金なら11時以降大丈夫です。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

2月5日（火）の13:00からで確定しました。
宜しくお願いしますー。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
了解です！
