### ISSUE TITLE
plz check if possible to get 2 pc for future designers (desktop or laptop)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#274]
tomorrow (1/24) check plz

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz check with Dimitar and ask supplier

**Comment by writerityelena** [comment]
@writerity-watanabe 
its possible if we decide specs

**Comment by writerity-watanabe** [comment]
@writerityelena 
same as our designers' pc

**Comment by writerityelena** [comment]
@writerity-watanabe 
if u accept offer that they will prepare, everything can be done until end of next week 
(my friend will give us discount again)

**Comment by writerity-watanabe** [comment]
@writerityelena 
about pc for designer,
spec -> check Dimitar
price -> me

**Comment by writerityelena** [comment]
@writerity-watanabe 
they are waiting for processors to arrive 
so today/tomorow we might have offer

**Comment by writerityelena** [comment]
@writerity-watanabe 
here is the offer , im checking with Dimitar also 
[AH1901PF00386 ВРАЈТЕРТИ .pdf](https://github.com/timeriver/company-management/files/2808330/AH1901PF00386.pdf)
