### ISSUE TITLE
Filip (architect)

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#281]
when we will pay the construction fee after sign the contract with owner

**Comment by writerityelena** [comment]
@writerity-watanabe 
-get offer for construction 
- pay 50% in advance , 50% after  finished work or pay all in advance depends

**Comment by writerity-watanabe** [comment]
@writerityelena 
to architect, have to pay 50% at least in advance (before start construction)?

**Comment by writerityelena** [comment]
@writerity-watanabe 
to constructors , first they prepare offer and also it can depend from what you agree with constructors 
you can pay in advance are all at once

**Comment by writerity-watanabe** [comment]
@writerityelena 
hmm 
so this is not an option
- pay after construction is done
or 
- 10% (or 20%) from fee in advance and the rest after finish

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz tell filip 
we would like to pay after construction is done if possible
(so that I can sign the contract with owner immediately

**Comment by writerityelena** [comment]
@writerity-watanabe 
okay i will tell
