### ISSUE TITLE
Take Hide and Kai to Public Office Revenue

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#282]

**Comment by writerityelena** [comment]
@writerity-watanabe 
today after work?

**Comment by writerity-watanabe** [comment]
@writerityelena 
no problem for me

**Comment by writerityelena** [comment]
@writerity-watanabe 
but Kai doesnt have the passport

**Comment by writerity-watanabe** [comment]
@writerity-watanabe 
tell me when we go there
> but Kai doesnt have the passport

i need to know more specific point
in that case, what would you do?

I cannot check message anytime and i need only final decision

**Comment by writerityelena** [comment]
@writerity-watanabe 
today we go for you 
next week i take Kai 
ok?

**Comment by writerityelena** [comment]
@writerity-watanabe 
next week we go
