### ISSUE TITLE
Feb Salary for Kai

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#291]
1 yen = 0.46mkd

---
350 * 3 * 20 = 21,000yen
500 * 3 * 20 = 30,000yen
350 * 2 * 20 = 14,000yen
350 * 2 * 13 = 9,100yen
= 74,100yen

= 74,100 * 046 = 34,086mkd - 2,494mkd
31, 592mkd = GROSS
NET = ??

**Comment by writerityelena** [comment]
@writerity-watanabe 
if gross is 34 086 NET will be 23041

**Comment by writerityelena** [comment]
@writerity-watanabe 
we put this salary in the contract ?
23 041

**Comment by writerity-watanabe** [comment]
@writerityelena 
ok

**Comment by writerity-watanabe** [comment]
@writerityelena 
I talked with Deni now about Kai's Feb salary
and he said I can give him money in cash for Feb salary but from March, it should be through bank account.

so in Feb, no need contract with Kai (plz start from March)
I will give him 23,041 in cash (for Feb).
also i will give him 11,089 in cash (for Jan)

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you check with accountant
GROSS 31, 592mkd
NET = ??

not urgent

**Comment by writerityelena** [comment]
@writerity-watanabe 

net- 21 414
contributions -  8 688 
personal tax- 1 490
