### ISSUE TITLE
Salary Payment to all staff on 2/11

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#293]
for Kai
https://docs.google.com/spreadsheets/d/1gQVA8bIgdn8eShJfTBIamwzf275MLeAOUIa1MQlqVlY/edit?ts=5a539538#gid=1449351496

**Comment by writerityelena** [comment]
@writerity-watanabe 
salary for Jan for Kai will be paid in cash? 
because we havent go to Public office revenue yet ...he doesnt have a number

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes for Jan and for Feb, in cash as i said

**Comment by writerityelena** [comment]
@writerity-watanabe 
then Ok
