### ISSUE TITLE
Serial Number of pc for each staff

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#294]
ex)
Dragana : DELL
Inspiron 15-7577

Dimitar : 
Mirjana : 
Zarko : 
Oliver : 

Jovica : 
Kire : 
Dragana : 

Elena : 
Bojan :

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityelena  We created the spreadsheet, but we don't have info for Zarko and Jovica's pc because they are absent. As soon as they are here we will update it.

https://docs.google.com/spreadsheets/d/1xfrYpLqJXgJxO3SRog6MkRj1YFjALCAXWC-diG5Pxus/edit?ts=5c4ec687#gid=0

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityelena Updated spreadsheet.

https://docs.google.com/spreadsheets/d/1xfrYpLqJXgJxO3SRog6MkRj1YFjALCAXWC-diG5Pxus/edit?ts=5c4ec687#gid=0

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
thanks
can you also update E and F?

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityelena 
https://docs.google.com/spreadsheets/d/1xfrYpLqJXgJxO3SRog6MkRj1YFjALCAXWC-diG5Pxus/edit?ts=5c4ec687#gid=0
