### ISSUE TITLE
Price for all equipment (pc, monitor, mouse, keyboard, UPS, mousepad...etc)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#295]
Write all in this google spreadsheet
https://docs.google.com/spreadsheets/d/1XOanOrVwNCHHoZ-RF6bAz-Ouq19ZkS5Wdx8wpaQ9aa4/edit?ts=5b88e19e#gid=450651484

for all staff except Yuko

ex) Jovica is using Mac mini, 2 monitors, a mouse, a mousepad, a keyboard and a headphone...

---
Mac mini：40,000mkd
1st monitor (specify serial number or brand)：10,000mkd
2nd monitor (specify serial number or brand)：8,000mkd
a mouse：300mkd
a mousepad：300mkd
a keyboard：200mkd
a headphone：1,000mkd

etc

**Comment by writerityelena** [comment]
@writerity-watanabe 
for this i should go to accountant to take all the invoices for equipment

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
