### ISSUE TITLE
Ask Filip to send us final design

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#296]
he said he was going to send us design pdf but not yet

**Comment by writerity-watanabe** [comment]
@writerityelena 
thanks

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz tell them
camera07 in the pdf
-> no need to put wall paper

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
- camera03 in the pdf
no need to paint the wall

- camera07
no need to put wall paper

- want to see a small phone booth on the ground floor


thats all, thanks
