### ISSUE TITLE
Ask Verica if possible to see new office with our client this week

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#297]

**Comment by writerity-watanabe** [comment]
@writerityelena 
first I will ask client when they are available to go

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz ask her if possible to visit this week after 1pm (anytime after 1pm)

**Comment by writerityelena** [comment]
@writerity-watanabe 
This Wed 13:00 she said
