### ISSUE TITLE
Withdraw 18,000MKD from Toki's account

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#31]
before I sent toki 18,000MKD from my private account cuz he wanted to try to use it in Japan 

He said, he does not need it and give me back

---
if you can send it to my account, it would be better

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz tomorrow when you go to back,
withdraw 18,000MKD from Toki's private card.

**Comment by writerityelena** [comment]
@writerity-watanabe 
its better to give you this money in cash because of taxations i think

**Comment by writerity-watanabe** [comment]
@writerityelena 
this is not company money
transfer from Toki's private account to my private account

but can be cash anyway
can be easier way

**Comment by writerityelena** [comment]
@writerity-watanabe yes i know 
i was talking about tax for your private account 
-reason for transfering money etc.
that is why people here rarely transfer money from account to account if they can return in cash

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
then cash plz 👍

**Comment by writerityelena** [comment]
@writerity-watanabe ok
