### ISSUE TITLE
Check insurance price and details of offer for new office

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#310]
Fire insurance

theft insurance
    need to protect equipment

...etc

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Together with Elena will go tomorrow to get an offer for the insurance of the new office

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
you have to go together? not either of you?

you just call if you need help

and also plz check with @writerityelena 
https://github.com/timeriver/company-management/issues/9

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I will go to ask about the insurance costs tomorrow.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I made a spreadsheet with one offer for now. I'm still waiting the other offer I contacted them again.
https://docs.google.com/spreadsheets/d/16jNHdhABNKgUqnZRyd5tHBg8PXcedr7EZ3yP_fc1Z9M/edit#gid=0

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
is it valid for how many years?
need to know
- how many is it valid for
- initial cost
- running cost

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe The insurance is valid for one year from the date of signing the contract. Payment is only once when the contract is signed and there are no additional costs. I updated the spreadsheet.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I received two more offers from different insurance companies and I will update the spreadsheet tomorrow morning

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityelena This is the last update for the insurance offers for the new office.

https://docs.google.com/spreadsheets/d/16jNHdhABNKgUqnZRyd5tHBg8PXcedr7EZ3yP_fc1Z9M/edit#gid=0
