### ISSUE TITLE
Create invoice to JP company for a few months

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#327]
for Oct
¥1,826,701

for Nov
¥1,714,611

for Dec
¥2,214,830

issue date should be end of Dec 2018

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes
we haven't made invoice for a few months as above i think

**Comment by writerityelena** [comment]
@writerity-watanabe 

we have for Oct = 1,826 701 and Nov= 1,714 61  we lack only  for Dec
¥2,214,830
 
![viber image 2019-02-07 10 18 39](https://user-images.githubusercontent.com/42862453/52401549-399b1e80-2ac2-11e9-8639-417224093dd8.jpg)
![viber image 2019-02-07 10 18 49](https://user-images.githubusercontent.com/42862453/52401550-3a33b500-2ac2-11e9-952e-cf82f9922cde.jpg)

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then plz

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://drive.google.com/open?id=1XKbvHULUHdZS9SAIFifKgLDeLpK5ZDze

**Comment by writerity-watanabe** [comment]
@writerityelena 
there are many files in that folder
plz tell me which one
I need file name so that i can find it right away

**Comment by writerityelena** [comment]
@writerity-watanabe 
oh i thought i sent right one, then Katsumok 013 :D
