### ISSUE TITLE
Create invoice to another JP company for Jan

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#328]
need to change 
> To: Katsumok Co. LTD /066-0414943 KATSUMOK CO.,LTD. 1-9-18, DAIMYO, CHU-O-KU, FUKUOKA          

Create•staffing Co Ltd (=I am checking this is correct, so plz wait for a while)
Ueno Building 5F, 5-20-7, WATANABE-DORI, CHU-O-KU, FUKUOKA
> Specification 

can you ask accountant
how can we write this below?

Kai is calling Japanese companies on the phone 
to ask if they need employee (recruitment) and he will make an appointment to explain more in person (he is just making an appointment with companies and another staff will go and explain more)
> Sum (write price and tax separately)

27,300 yen
+
Tax (8% in Japan)

= 29,484yen

plz copy this template below and make another one for this
https://docs.google.com/document/d/1Q4Pbmv-frDyOTcIz9wS7oq1FFjdESGYx1CsOaetXlxE/edit

**Comment by writerityelena** [comment]
@writerity-watanabe 
btw 
as number of employees increased also the price changes that is how accountant said, so from next month i think for accounting invoice will be 12 000 MKD

**Comment by writerityelena** [comment]
@writerity-watanabe 

Writerity is issuing this invoice to Create Staffing Co. LTD  for the Services that Kai does?

**Comment by writerityelena** [comment]
@writerity-watanabe 

from accountant about new prices 
[isos odluka.pdf](https://github.com/timeriver/company-management/files/2827152/isos.odluka.pdf)

**Comment by writerity-watanabe** [comment]
@writerityelena 
btw you are sending this to wrong task

**Comment by writerity-watanabe** [comment]
@writerityelena 
for this task, https://github.com/timeriver/company-management/issues/328#issue-405722758

company name is 

> Create•staffing Co Ltd

plz make invoice for this

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz do this week

**Comment by writerityelena** [comment]
@writerity-watanabe 
i shared on drive pls check

**Comment by writerity-watanabe** [comment]
@writerityelena 
edited plz print (this is for Jan only)
we use it for this month (Feb) also 
plz save it as template here
https://drive.google.com/drive/folders/1B9coFeymVM_qjbUfOIXWyVMaPC45oLNh

**Comment by writerity-watanabe** [comment]
@writerityelena 
> 27,300 yen
+
Tax (8% in Japan)

= 29,484yen

plz separate price and tax in invoice

**Comment by writerityelena** [comment]
@writerity-watanabe 
accountant said must be all calculated  / sum
we cant separate tax and price 
exepct i can add as Note: 8% tax included ?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then
plz add Note

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you send me pdf for the invoice? i need to send it to client

**Comment by writerityelena** [comment]
@writerity-watanabe 
check here if its ok?
https://drive.google.com/drive/folders/1NBXsFGo45F5NEgTV-399nvM5MSQGhSq4

**Comment by writerity-watanabe** [comment]
---memo---
done payment from them and checked with KATSUMOK
