### ISSUE TITLE
Company Account for Andrej

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#331]
▼gmail (already created) 
writerity.andrej.lazarevski@gmail.com
test123%%
＊let him change personal information for gmail account (cuz Hide created it and the information is mine now)

▼@writerity.com mail
a.lazarevski@writerity.com
lax75x5618cz

▼slack (already invited, check email accept it)
writerity-dev.slack.com

▼skype (not yet)
plz create and invite him to necessary group

▼chatwork (already invited, check email and accept it)

...

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Andrej created the accounts.
