### ISSUE TITLE
advice to Kai about Research task 2/3

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/company-management#332]

**Comment by writerityyuko** [comment]
@writerity-kai @writerity-watanabe 

お休みのところ、すみません。
リサーチの件で、金曜日に質問を受けてからずっともやもやしていて、すっきりさせたかったことがあり、以下お知らせしておきます。（ボランティアということで、残業は申請しません。＞渡邊さん。）

見てほしいことはすでに共有済みのリサーチシートに反映させてあります。特にみてほしいところは赤字にしています。

https://docs.google.com/spreadsheets/d/1JF6SO-rPTGrr4x31hR44PY5Wf7BK4uzd9lHqGal8gZw/edit#gid=929171364

**１．プレリサーチの実施について**

ずっと、なんとなくしっくりこなかったのは、まったくの予備知識なしに実際に入っていたからだと気づき、時間もないので少し自分でプレリサーチをしてみました。
（何かを調べるときって、最初に予備知識を得るためのプレリサーチをしてから、実査の設計をするんですね。そこで分かった情報はたいてい実際の調査項目のいくつかを先取りすることになる。）

で、その結果を、「DB検索ログ」と「情報ソース」タブにまとめていますので、ご覧ください。

プレリサーチで分かったのは、結構公開情報がリッチだということです。たぶん大まかな業界構造はささっとわかるんじゃないでしょうか。
ひとまず私が拾った情報で使えそうなのはリストアップしてみたので、情報ソースをよく見てみてください。調査項目A-4に該当する情報も結構ありますので、報告に使えると思います。


**２．調査手法について**

調査設計のタブを見てほしいのですが、フェーズ１を少し重くしました。やはりこの時点で概況がわかっていたほうがよいので。
それからフェーズ２以降の調査手法を、一次情報をより取りに行く手法に変えました。このほうが早いし、うちの名前での活動であれば、クライアントにとってはリスクゼロなので。（一次情報というのは、実際に自分で見聞きしたりして集めた情報のこと。デスクリサーチとかで拾う情報は誰かを介した情報で二次情報といいます。）　こちらの準備が整えば（仕事取ってきても大丈夫な体制なら）、プレマーケティングをかけながら情報収集するのもいいかなと思います。たぶん時川さんのイメージに近いんじゃないでしょうか。

**３．業界団体への入り込み**

業界団体（IAB）の会員になることを強く勧めます。
情報は取りやすくなるし、コネクションを築くきっかけになると思いますので、ぜひご検討ください。クライアント名だとクライアントが欧州進出を企図していることが気づかれる可能性があるので、うちが登録するのが良いと思います。

**４．ウェブ広告制作会社のKFS（成功要因）**

これがわからないんですよね。まだ。ないが制作会社として成功する要因なのか。
早い、安い、なのか？
なんか特別なコンテンツを持ってるとかなのか？
品ぞろえが豊富だ、とかなのか？

今の共有している調査項目って、どの業界でも使える汎用的なものを列挙しているんですけど、
たぶん、こうじゃないような、、、という気がしているんです。
（以前開地さんと仕事したときにも、はっきりとこれだ、というものを掴めなかったのです。）
このKFSについて少し仮説があれば、調査項目をもうちょっとクライアントがいる業界用にフィットさせることができるんですが。。
もしクライアントと話していてなんかその辺の話を聞いたことがあれば、教えてください。


以上、もし月曜日の打ち合わせに使えることがあれば使ってください。
月曜の朝必要であれば話しましょう。

**Comment by writerity-kai** [comment]
@writerityyuko 
坂口さんお休みにも関わらず本当にありがとうございます。
本当にリサーチに関してゼロ知識の中、模索していた中でスプレッドを作成して頂き、またGITHUBに記載頂いた内容を拝見し勉強になります。
月曜日では改めて㋃までのスケジュールを立て直し、必要な検討項目等に関しても江村さんとお話していきます。
また明日、1日4時間の業務時間に増やして頂くよう江村さんにもご相談致しますが、それでも2ヶ月で160時間しか業務時間がないため、検討項目の削減や、調査項目数は維持で調査情報量を削減する等の対応が必要になると考えております。
この点以外でもで明日、質問がございましたらお伺いするかもしれませんが宜しくお願い致します、、
お休みの中本当にありがとうございました！

**Comment by writerity-watanabe** [comment]
@writerityyuko 
こちら、ありがとうございました！
業務量に関わるところで、少し相談ありますので、
今日の14時くらい？でミーティング可能でしょうか？

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> 今日の14時くらい？でミーティング可能でしょうか？

承知しましたー。
