### ISSUE TITLE
Accountant rulebook

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#336]

**Comment by writerityelena** [comment]
@writerity-watanabe 

DECISION to pass an act for minimal costs for accounting

Article 2
Point 9….(from macedonian verison)
For small companies and non profit organizations  with annual profit of 10.000.001,00  to 15.000.000,00 MKD 
With at least 5 employees and more than 10 outgoing Invoices 
More bank statements in at least  2 banks… price is:
10500+18% VAT Tax  = 12 390

*accountant said this point is for our Company

**Comment by writerity-watanabe** [comment]
@writerityelena 
so we pay 12,390MKD from next month?
till how many people? same?

**Comment by writerityelena** [comment]
@writerity-watanabe 
employees do not count that much , the most important is the profit 
so for Jan we shall pay 12 390
