### ISSUE TITLE
Company Account for Aleksander

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#337]
▼gmail (already created)
writerity.aleksandar.mihailovski@gmail.com
test123%%
＊let him change personal information for gmail account (cuz Hide created it and the information is mine now)

▼@writerity.com mail
a.mihailovski@writerity.com
mr64zig21pma

▼slack (already invited, check email and accept it)
writerity-dev.slack.com

▼skype (not yet)
plz create and invite him to necessary group

▼chatwork (already invited, check email and accept it)

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Aleksandar created the accounts.
