### ISSUE TITLE
Check invoice from JP company (Ones)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#349]

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes they haven't sent

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz check this
[writerity_2____.pdf](https://github.com/timeriver/company-management/files/2841745/writerity_2____.pdf)

**Comment by writerityelena** [comment]
@writerity-watanabe 
sent to accountant , tomorrow they will tell if everything is ok so we can proceed

**Comment by writerityelena** [comment]
-invoice should be 2018 or 2019? 
(because we havent submit yet, we dont know if Public Office Revenue will allow release from withheld tax)
-and we need signature from JP Company

**Comment by writerity-watanabe** [comment]
@writerityelena 
2018 
[writerity_2____ (1).pdf](https://github.com/timeriver/company-management/files/2844297/writerity_2____.1.pdf)

this stamp is not allowed?

**Comment by writerityelena** [comment]
@writerity-watanabe 
stamp +signature

**Comment by writerity-watanabe** [comment]
@writerityelena 
will ask

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz check (send zip file because it was too big file)
[invoice 001.pdf.zip](https://github.com/timeriver/company-management/files/2845776/invoice.001.pdf.zip)

**Comment by writerityelena** [comment]
@writerity-watanabe 
still no signature on the Invoice , pls tell them 
- signature 
- scan 
- send t Writerity

**Comment by writerity-watanabe** [comment]
@writerityelena 
[invoice 001.bmp.zip](https://github.com/timeriver/company-management/files/2851288/invoice.001.bmp.zip)

here signature
<img width="1280" alt="2019-02-11 14 54 24" src="https://user-images.githubusercontent.com/36668646/52567571-f536b800-2e0c-11e9-9bd2-2bec4f391c68.png">

**Comment by writerityelena** [comment]
@writerity-watanabe 
i couldnt open the file before but now is ok tnx
