### ISSUE TITLE
Get profit and loss sheet and B/L sheet for 2018

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#350]
we really need it tomorrow

**Comment by writerity-watanabe** [comment]
@writerityelena 
I already talked to Deni and he will call them tomorrow 
so plz talk to Deni first and check 
then if needed we will ask accountant

**Comment by writerityelena** [comment]
@writerity-watanabe 
''I already talked to Deni and he will call them tomorrow
so plz talk to Deni first and check
then if needed we will ask accountant"
about?

**Comment by writerity-watanabe** [comment]
@writerityelena 
we will see after Deni call
plz talk to deni

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok
