### ISSUE TITLE
Elena - next contract (expire on 2/28)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#354]

**Comment by writerityelena** [comment]
@writerity-watanabe 
can u check 
https://docs.google.com/document/d/1TVqpIkLCO2OyvSdfmLM3KnojqGvgiAphFfcaXJEQ-uo/edit

**Comment by writerityelena** [comment]
@writerity-watanabe i can print?

**Comment by writerity-watanabe** [comment]
@writerityelena 
access permission plz

you just updated contract period or sth right from your previous contract

**Comment by writerityelena** [comment]
@writerity-watanabe everything the same , i just updated period yes
