### ISSUE TITLE
DIGITAL CERTIFICATE for electronic signing

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#363]

**Comment by writerityelena** [comment]
@writerity-watanabe 
we need this certificate for our company , before i submit documents to employment agency first i should publish advertisement on their web page with support of this certificate. 
An digital certificate is a base for secure exchange of documents in modern communication. By using them you provide:
**Authentication** - the CA verifies the identity of the certificate holder in the issuing process.
Integrity - the digital signature provides the recipient a guarantee that the received signed data is unchanged.
**Nonrepudiation** - the signer of data cannot deny the origin of the signature because he is the only one with access to the private key by which the signing was done.
Cost : 
HDD of the PC = 1680 MKD 
PKI Token = 3 020. MKD

**Comment by writerity-watanabe** [comment]
@writerityelena 
not now if its not urgent
