### ISSUE TITLE
Update "PC Management" spreadsheet

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#365]
https://docs.google.com/spreadsheets/d/1IR4HOxYVxPEl4OTeCTNM05UkgkTVEbIEzeWT7u_SSU0/edit#gid=477820687

till today

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz finish this by 20th Feb

**Comment by writerityelena** [comment]
@writerity-watanabe 
as i can see you have updated?

**Comment by writerity-watanabe** [comment]
@writerityelena 
not at all 
you should see more carefully.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko @writerityelena I updated the sheet with specifications from Kire and Jovica's PC.

https://docs.google.com/spreadsheets/d/1IR4HOxYVxPEl4OTeCTNM05UkgkTVEbIEzeWT7u_SSU0/edit?ts=5c74f395#gid=477820687

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
thanks
