### ISSUE TITLE
Take bank statement for Feb and take missing receipts

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#370]
from this Feb, every month we should do
to avoid to be in hurry before year-end closing

**Comment by writerityelena** [comment]
@writerity-watanabe 
ok

**Comment by writerityelena** [comment]
@writerity-watanabe 
btw what missing receipt?

**Comment by writerity-watanabe** [comment]
@writerityelena 
if we dont have receipts for the list in the statement
