### ISSUE TITLE
Share with staff about holiday and extra leave

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#387]
plz share with all staff about leave
- if someone' death in family or his marriage (maybe more, ask Deni if need) → extra leave (not counted as holiday)
- if sickness and absent with certificate,
→ extra leave 

I think there is limit number to use
so plz check if needed more to know

and also share this
- if want to use paid holiday for a day, then need to tell at least 2days in advance
- if want to use paid holiday for multiple days, then need to tell at least 2 weeks in advance

**Comment by writerityelena** [comment]
@writerity-watanabe 


* if someone' death in family or his marriage (maybe more, ask Deni if need) → extra leave (not counted as holiday) => this day is like gift from company?

* if sickness and absent with certificate,
  → extra leave => same like before , no deduction?

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz check law
Deni said its like that
