### ISSUE TITLE
Check rule books

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#394]
plz share with all staff about leave

* if someone' death in family or his marriage (maybe more, ask Deni if need) → extra leave (not counted as holiday)
* if sickness and absent with certificate,
  → extra leave

I think there is limit number to use
so plz check if needed more to know

**Comment by writerityelena** [comment]
@writerity-watanabe 
about annual vacation leave:
Annual vacation is normally used during the calendar year.
annual vacation can be used in many parts,  with one part of annual leave having to last at least two uninterrupted working weeks , that is 12 working days which the employee is obliged to use by the end of the current calendar year, and the rest to June 30 next year. 
The annual leave that has not been used in the current calendar year due to absences due to sick leave or injury  the worker has right to use until  June 30 of the next calendar year.(this is why those who spent paid days for 2018 should wait until June 30 for new paid days)  this Deni confirmed also

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay plz explain to employees 
(but we use paid holidays in advance in end of Apr (Japanese long holidays)
so in this case, we can do that and we can let them use some before Jun30?

**Comment by writerityelena** [comment]
@writerity-watanabe 
we can, its up to the company

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay first plz explain this is the basic rule and let them understand
https://github.com/timeriver/company-management/issues/394#issuecomment-463957094

and then i will add 
> we might use paid holidays in advance at the end of Apr (Japanese long holidays) or new year
so in this case, you can use in advance before Jun30
