### ISSUE TITLE
Research about registered trademark

### ISSUE THREAD

**Issue by writerity-kai** [timeriver/company-management#396]
Can I ask you to research for cost and  amount of time about  registration of trademark ,If I apply for it in Macedonia or EU.
I might apply new services’s name” as registration of trademark .

**Comment by writerity-kai** [comment]
Maybe,this research  is very difficult.
If you have question , you can ask me anytime.

**Comment by writerity-t-bojan** [comment]
@writerity-kai I contacted several law firms in Macedonia to get more information about cost, time, procedure for registration a name of a new service as a trademark. I will update you as soon as have any information back.

**Comment by writerity-t-bojan** [comment]
@writerity-kai @writerityelena I have received two offers about registration the name of the service as a trademark. I am awaing a couple more and I will create spreadsheet with offers to compare and analyze.

**Comment by writerity-t-bojan** [comment]
@writerity-kai @writerityelena This is a sheet with offer from three companies for intelectual property regarding registration of a trademark in Macedonia.

https://docs.google.com/spreadsheets/d/1PIixGPimaqbDxLPx_SuZoCoBus9wkWL2LCjiaKQRbFA/edit#gid=0

**Comment by writerity-t-bojan** [comment]
@writerity-kai @writerityelena updated sheet 
https://docs.google.com/spreadsheets/d/1PIixGPimaqbDxLPx_SuZoCoBus9wkWL2LCjiaKQRbFA/edit#gid=0
