### ISSUE TITLE
Notary

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#404]
renewing contract for this apartment that includes Kai instead of Chinatsu

**Comment by writerityelena** [comment]
@writerity-watanabe 
today?

**Comment by writerity-watanabe** [comment]
@writerityelena 
this is for...?

**Comment by writerityelena** [comment]
@writerity-watanabe 
renewing contract for this apartment that includes Kai instead of Chinatsu

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay we go this afternoon

**Comment by writerityelena** [comment]
@writerity-watanabe im available anytime
