### ISSUE TITLE
Check if possible to rent some money from bank without guarantor

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#408]
- condition to do that
- how much interest (yearly?)

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz do this today.
this is urgent task

**Comment by writerityelena** [comment]
@writerity-watanabe 
I need to know: 
-amount 
-we rent as company or as person (example Toki will rent) ?

**Comment by writerityelena** [comment]
@writerity-watanabe 
the Bank allows credit to a company, but they said the best is to go in person to negotiate 
Credit depends from the Company's profit , if we have bigger profit the loan can be bigger

**Comment by writerity-watanabe** [comment]
@writerityelena 
no guarantor needed right

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes without guarantor

**Comment by writerity-watanabe** [comment]
---memo---
depends on profit from company
- 20% must be our money (ex, can loan 10,000EUR if the total amount of equipment is 12,500EUR)
- 6.5% interest
