### ISSUE TITLE
Writing email

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#419]

**Comment by writerityelena** [comment]
@writerity-watanabe pls tell if i missed some details?

Dear Japan Airlines,


As a frequent customer of yours we are  writing this email in regards of  the last tickets we bought from your company. 

First we would like to provide you some more info about the passenger named Takaaki Kinpara and the ticket we are concerned about is about the following destination:
Helsinki (HEL) - Tokyo (NRT) Japan Airlines による運航
Reservation No.4221515607
Eventually, we assume that there might be double payment i.e double booking for the same destination. 
The main question we would like to ask is, did Turkish Airlines buyt a ticket back to Japan for the same passenger?

We would appreciate if your company would compensate so that we can have a chance to provide a better experience next time we fly.

If you have further questions regarding this issue , please feel free to contact us.
Sincerely,
Elena

**Comment by writerity-watanabe** [comment]
@writerityelena 
better to include;
his flight from Skopje to istanbul delayed
and Turkish Airlines bought him a new ticket to Helsinki but we thought they will give us a ticket to go back to Japan as well but your passenger don't speak English so we bought a new ticket for that.
-> that is why 
> The main question we would like to ask is, did Turkish Airlines buy a ticket back to Japan for the same passenger?

**Comment by writerityelena** [comment]
@writerity-watanabe is this better explanation of the situation?

Dear Japan Airlines,


As a frequent customer of yours we are  writing this email in regards of  the last tickets we bought from your company. 

First we would like to provide you some more info about the passenger and introduce you with the situation. 
The passenger is named Takaaki Kinpara and the ticket we are concerned about is about the following destination:
Helsinki (HEL) - Tokyo (NRT) Japan Airlines による運航 with reservation No.4221515607
His flight from Skopje to Istanbul was delayed, for that reason Turkish Airlines from Skopje bought him a new ticket to Helsinki. After Helsinki he should have arrived in Japan.
Since our passenger doesn’t speak English and we didn’t received any confirmation about the ticket that Turkish airlines bought , in meantime we also bought new ticket for the same direction from our private account.

Eventually, we assume that there might be double payment i.e double booking for the same destination. 
The main question we would like to ask is, did Turkish Airlines buy a ticket back to Japan for the same passenger?

We would appreciate if your company would compensate so that we can have a chance to provide a better experience next time we fly.

If you have further questions regarding this issue , please feel free to contact us.
Sincerely,
Elena

**Comment by writerity-watanabe** [comment]
@writerityelena 
yes

**Comment by writerityelena** [comment]
@writerity-watanabe 
okay i will send this and put you in CC

**Comment by writerity-watanabe** [comment]
@writerityelena 
thanks

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://faq-ar-en.jal.co.jp/app/ask_ar?_ga=2.92986713.553962311.1550829894-1133328122.1550829894

**Comment by writerityelena** [comment]
@writerity-watanabe 
I will need:
-JMB Number
-E-ticket Number
-Flight Number

**Comment by writerity-watanabe** [comment]
@writerityelena 
they replied to me and they cannot do anything about it
so I will try to reach Turkish airlines

**Comment by writerityelena** [comment]
@writerity-watanabe 
should we send this email to Turkish airlines?
