### ISSUE TITLE
Update [inner]Writerity

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#421]
2/25 or 2/26 finish
https://docs.google.com/spreadsheets/d/1QRt6JSpdk0_ulCKDk4ZEjCiNOfMDHMR0nNg_LJ2_rvY/edit?ts=5a53932f#gid=474459662

expense or non-expense

**Comment by writerityelena** [comment]
@writerity-watanabe 
?

**Comment by writerity-watanabe** [comment]
@writerityelena 
already forget?
![inner writerity google](https://user-images.githubusercontent.com/36668646/53324238-98450280-38e0-11e9-8fde-25c295def54d.png)

**Comment by writerityelena** [comment]
@writerity-watanabe 
i didnt forget its already updated for 2019

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then

**Comment by writerityelena** [comment]
@writerity-watanabe np

**Comment by writerity-watanabe** [comment]
@writerityelena 
also "0,business card history"?
if we use business card for only expenses, then no need
but for example i use business card for airplane ticket for clients (if we better not use for that, then we probably won't next time

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes, only for expenses 
tickets are not Company expenses because clients are not employed in Writerity

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay so next time we better not use it as i understand

**Comment by writerityelena** [comment]
@writerity-watanabe yup

**Comment by writerity-watanabe** [comment]
@writerityelena 
but then what about for this?
![inner writerity google](https://user-images.githubusercontent.com/36668646/53324978-7c426080-38e2-11e9-8fad-5d03d3cd438c.png)

**Comment by writerityelena** [comment]
@writerity-watanabe those are for the clients right?

**Comment by writerity-watanabe** [comment]
@writerityelena 
dont know details from the Title but i think yes
