### ISSUE TITLE
Invoice of accommodation for client

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#422]
[0975_001.pdf](https://github.com/timeriver/company-management/files/2899572/0975_001.pdf)

**Comment by writerityelena** [comment]
@writerity-watanabe 
you paid this with company's money or?

**Comment by writerity-watanabe** [comment]
@writerityelena 
no but just keep it if we can use for something

**Comment by writerityelena** [comment]
@writerity-watanabe 
ah ok 👍
