### ISSUE TITLE
Tell accountant we have to rush payment to Ones because we have deadline to finish payment (end of Feb)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#423]

**Comment by writerityelena** [comment]
@writerity-watanabe 
we are waiting them to give use official tax number so we can do the payment and the good news are that they allowed release from witholding tax! :DD 
For that reason this is the situation  https://docs.google.com/spreadsheets/d/1j-PRKFohLbYrM1H_Y3rq3ImaNSKP1oEYRAbIEeS1r64/edit?userstoinvite=trs.watanabehidenori%40gmail.com&ts=5c6c2fab#gid=693745069

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks
