### ISSUE TITLE
invoice to KATSUMOK (Dec)

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#43]
plz finish 
i have to sign 

https://docs.google.com/document/d/1Q4Pbmv-frDyOTcIz9wS7oq1FFjdESGYx1CsOaetXlxE/edit

**Comment by writerity-watanabe** [comment]
@writerityelena 
plz create invoice like last month
¥1,714,611

now i am asking them if its correct, but in case they dont reply tomorrow

**Comment by writerityelena** [comment]
@writerity-watanabe 
so i should wait before printing?

**Comment by writerityelena** [comment]
@writerity-watanabe 
due date?

**Comment by writerity-watanabe** [comment]
@writerityelena 
today or tomorrow 
plz print and i will sign just in case they dont reply

**Comment by writerity-watanabe** [comment]
@writerityelena 
thanks

**Comment by writerityelena** [comment]
@writerity-watanabe 
this one has better quality 
[Invoice 12 Katsumok.pdf](https://github.com/timeriver/company-management/files/2699040/Invoice.12.Katsumok.pdf)
