### ISSUE TITLE
Print and signing of the new Rulebook on annual vacation leave

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/company-management#434]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I made an update on the rulebook for the annual vacation leave, according to the latest changes in the macedonian labour legislation. The update is in track changes. Please advise if it is ok to print and to be ready for signing. Thanks.

https://docs.google.com/document/d/1h0VvvYxX9ZASii0Cxb7psRrXt70hMo3i5PJQGMZ34cg/edit

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

I think it is fine.
please Wait for Hide's final approval.
thanks for your work.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay
thanks
