### ISSUE TITLE
筒井さんインターン在籍証明書

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#45]
https://docs.google.com/document/d/1j5YJKSfdwpuCHoL3LQVqKNO7yc4jILgfgES31hngbq0/edit

---
在籍証明書の発行
・1年インターンシッププログラムに参加。在籍は半年。自己都合による帰国
・WEB開発サポートおよび新規事業開発アシスタント業務に従事

**Comment by writerityyuko** [comment]
筒井智菜津 | 筒井智菜津 | 2019/01/17 17:49 (14 時間前) |   |  
-- | -- | -- | -- | --
筒井智菜津
To Writerity | To Writerity
To Writerity

坂口さん
こんにちは！

遅くなってしまい申し訳ありません。

在籍証明書の件承知しました。
マケドニアでのことなので、私の現住所の項目はなしでお願いします。
可能でしたら、マケドニアでの住所で大丈夫です。

生年月日は、1996年7月26日です。

宜しくお願い致します。


筒井

**Comment by writerityyuko** [comment]
@writerity-watanabe 

忘れたころに、、という感じですが、筒井さんから在籍証明に関するお返事を2か月遅れで頂いたので、発行しようと思うのですが、
いつから就業開始したか、記録残っていますでしょうか？

原稿はこちらです。

https://docs.google.com/document/d/1j5YJKSfdwpuCHoL3LQVqKNO7yc4jILgfgES31hngbq0/edi

**Comment by writerity-watanabe** [comment]
@writerityyuko 
開始は4/2月からとしていました！
（契約書等は、もしかしたらエレナが作成していたかもしれません）

**Comment by writerityyuko** [comment]
@writerity-watanabe 

了解です。確認しますね。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

念のためこっちもメンションしときます。
急ぎじゃないですが。。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ありがとうございます！
問題ないです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

はいー。そしたら印刷するのであとでサインくださいー。
