### ISSUE TITLE
Add contract info for Writerity Staff

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#451]
Andrej and Aleksander
and sth else if there is 

https://system.writerity.com/wp-admin/edit.php?post_type=t_increase_history

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I don't have username and password.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
writerity.bojan.tasevski@gmail.com
test123

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Do you have a moment I have a problem opening this system.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
you can ask Elena first
She can open it
