### ISSUE TITLE
Copy of Recommendation for Kai

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#453]
plz print and keep it for a while

for work permit

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Does something has to be attached in this task?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
ah this one
[山崎海Letter of recommendation.pdf](https://github.com/timeriver/company-management/files/2930561/Letter.of.recommendation.pdf)
