### ISSUE TITLE
Invoice for KATSUMOK for Feb

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#454]
¥2,533,268

plz create an invoice for this

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe which will be date of issue?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
today okay

**Comment by writerityelena** [comment]
[Writerity_003.pdf](https://github.com/timeriver/company-management/files/2929935/Writerity_003.pdf)
@writerity-watanabe
