### ISSUE TITLE
Update contract for Writerity staff

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#458]
system and contract folder

https://system.writerity.com/wp-admin/

https://drive.google.com/drive/folders/1djXfYXeG-ZC5c43JEGBHzclDBHKlIfXk

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan @writerityelena 
are you sure if everything is in the system and in the folder?

**Comment by writerityelena** [comment]
@writerity-watanabe 
today we updated , is there anything missing?

**Comment by writerity-watanabe** [comment]
@writerityelena @writerity-t-bojan 
in system

correct?
![t_increase_history writerity system wordpress 1](https://user-images.githubusercontent.com/36668646/53896088-a2c77080-4033-11e9-8b3c-48d71b406408.jpg)


and there is no current contract for Zarko
Jovica's contract for 2019/01/15 dont have cc

...etc
