### ISSUE TITLE
Share plan for when you finish to give tasks to Bojan

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#463]
want to know when

**Comment by writerityelena** [comment]
@writerity-watanabe 
Monday, Tuesday , Wednesday 
-introducing with spredsheets , updating bank history , collecting materials for accountant 

Thursdat, Friday 
-doing payments with token

**Comment by writerity-watanabe** [comment]
@writerityelena 
so from next week, he can do it by himself?

**Comment by writerityelena** [comment]
@writerity-watanabe 
I think yes , depends from him
