### ISSUE TITLE
Want to transfer money to Kai's private bank account here

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#464]
plz check if there is anything we have to be careful with

deadline is 3/7
because Kai will go back to Japan on 3/8

**Comment by writerityelena** [comment]
@writerity-watanabe 
today right?
how much would you like to transfer?

**Comment by writerity-watanabe** [comment]
@writerityelena 
not today
if we can transfer money to his bank account without any problem, we will transfer money on 10th April and May like salary (but its just private money from me

the amount will be around 40,000mkd and 50,000mkd

**Comment by writerityelena** [comment]
@writerity-watanabe 
no problem to transfer up to 2500 Eur

**Comment by writerity-watanabe** [comment]
@writerityelena 
i can go to bank and do it right?

**Comment by writerityelena** [comment]
@writerity-watanabe yes
