### ISSUE TITLE
Give permission to specific users to see/edit the google spreadsheet / document / PDF..etc

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#465]
check all document / spreadsheet / PDF

![writerity google](https://user-images.githubusercontent.com/36668646/53939575-c3370f80-40b3-11e9-8677-ebf339cb5afa.png)

**Comment by writerityelena** [comment]
@writerity-watanabe 
which documents and who is included as specific user?

**Comment by writerity-watanabe** [comment]
@writerityelena 
all the documents

and depends on the document

**Comment by writerityelena** [comment]
@writerity-watanabe got it
