### ISSUE TITLE
look for one internship student

### ISSUE THREAD

**Issue by writerity-kai** [timeriver/company-management#472]
I ask you to look for one internship student.
【Job contents】
①public relations
●playing game traning  game(smash bros)
●take picture(playing game) and uplord our company BLOG.

②development of new system
●Undecided detail

【conditions】
・Good appearance(looks) cute...beatiful...only women

**Comment by writerity-kai** [comment]
when you have time,plz look for person.

**Comment by writerity-t-bojan** [comment]
@writerity-kai can you please give more information about?
1. What kind of intern student do we need, which area of expertise?
2. What will be his exact role in the company, working hours, etc?
3. Can you please explain more about
②development of new system
●Undecided detail
4. 【conditions】
・Good appearance(looks) cute...beatiful...only women
Regarding this requirement, I must say that it's a bit of discriminatory based on the sex and will attract only bad publicity for us as a company and as indivuduals.
5. Will be there any compensation?
6. What kind of skills and qualifications does an intern student must have?

**Comment by writerity-kai** [comment]
What kind of intern student do we need, which area of expertise?
→①public relations（take picture  or video→student Play game）, and put on picture or video to our Blog ）②development new system(undecided detail)
What will be his exact role in the company, working hours, etc?
Can you please explain more about

**Comment by writerity-t-bojan** [comment]
@writerity-kai can you please tell me more:
2：What will be his exact role in the company, working hours, etc?
→ We ask her to spread our company and create new any system.
- What kind of system will he/she create?
→Our new business which we'll sell video(self-introduce) is needed automatic transmisson system(sent Email to companies).
- Can you please explain more, I don't quite understand this part. What kind of video will be?
- Will the student be playing game and then put that video on blog as well?

**Comment by writerity-kai** [comment]
●Can you please explain more, I don't quite understand this part. What kind of video will be?
→self introduce video
for example  We sell video to MacDonald hamburger shop.
(MacDonald　want to spread myself(MacDonald) to the world.
For that, the company want video which introduce myself.

can you understand by my english?

Will the student be playing game and then put that video on blog as well?

**Comment by writerity-t-bojan** [comment]
@writerity-kai:
Intern 
•	Promoting the company via effective Company communications (comfortable to create marketing self-introducing advertisement videos),
•	Gaming-enthusiast, comfortable to play a game on a console and upload the video on a blog,
•	Web development skills are preferable (Junior Web Developer ※reference our website),
•	Great knowledge of English language, both spoken and written,
•	Solid communications skills,
•	A student in the last year of studies (preferably at one of the technical universities).
I think it is better without this part (Junior Web Developer ※reference our website), because we will have bigger chances to find a student who is will be interested in this kind of work.
Is it ok?

**Comment by writerity-kai** [comment]
@writerity-t-bojan 
It's Okay!
thank you.
Please,look for student,when you have a time.:)

**Comment by writerity-kai** [comment]
@writerity-t-bojan 
Hi,bojan.
Did you finish finding internshipstudent?
Can I look at internshipstudent's picture?

**Comment by writerity-t-bojan** [comment]
@writerity-kai Hi, Kai.
We found intern student, she is starting on Monday.
[CV_ENG_Angelina_Markova.pdf](https://github.com/timeriver/company-management/files/2995639/CV_ENG_Angelina_Markova.pdf)
