### ISSUE TITLE
[Paypal]Check what is wrong

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#490]
<img width="388" alt="スクリーンショット 2019-03-12 08 34 15" src="https://user-images.githubusercontent.com/36668646/54182473-dfff8880-44a1-11e9-9668-b5bb73f83c36.png">

 "Our client tried to send the money via paypal
But this appeared "

**Comment by writerityelena** [comment]
@writerity-watanabe so they tried to send to our account , and according to this message we accept payments only through our website?

**Comment by writerity-watanabe** [comment]
@writerityelena 
maybe i have no idea
plz try something

**Comment by writerityelena** [comment]
@writerity-watanabe can i try with your card or mine? 
transfer some small money like 1$

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay from yours
will give back later

**Comment by writerityelena** [comment]
@writerity-watanabe np

**Comment by writerityelena** [comment]
@writerity-watanabe 
i tried from my account with my card and the result is :
![image](https://user-images.githubusercontent.com/42862453/54204341-587f3d00-44d4-11e9-8be1-f9d01314f888.png)

so its about the Country

**Comment by writerity-watanabe** [comment]
@writerityelena 
so you are saying
we can send money from this account but
we cannot receive any money in this paypal account?

**Comment by writerityelena** [comment]
@writerity-watanabe 
i will try to send money from Writerity account to my account just a sec

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes we can send 
![image](https://user-images.githubusercontent.com/42862453/54204751-2fab7780-44d5-11e9-9bc5-a328e261c6df.png)

**Comment by writerityelena** [comment]
@writerity-watanabe 
![image](https://user-images.githubusercontent.com/42862453/54205460-a9903080-44d6-11e9-9a07-26ea26c3a004.png)

**Comment by writerityelena** [comment]
@writerity-watanabe 
and it was canceled 
![image](https://user-images.githubusercontent.com/42862453/54205558-e1977380-44d6-11e9-8093-5e20e2b5a971.png)

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay 
now I sent email to paypal and asking why

**Comment by writerity-watanabe** [comment]
---memo---
got message from paypal

---
Dear Writerity Inc,

Thank you for contacting PayPal regarding your concern.

I have reviewed your account and can see that you currently have a Macedonian account. Currently, PayPal accounts in Macedonia are unable to use our services to receive payments. When we offer our service to a country, we need to ensure that we are compliant with both local and international laws before we can offer our full service.

Due to the challenges and complexities associated with the worldwide financial network, we cannot offer a firm date or timetable for expansion of specific services. We can promise you that we are working hard to enhance our service within the nations where we are offered.

To see which countries may only send money, go to www.paypal.com/us and click the USA flag in the bottom right corner of the page. I recommend that you visit this page often to review updates and new capabilities for our worldwide users.

Thank you for using PayPal.

Yours sincerely, 
Alise 
PayPal

**Comment by writerityelena** [comment]
@writerity-watanabe so we check for updates ...
