### ISSUE TITLE
Buy 3 Tickets for M3-CON Conference of Computer Graphics and Animation

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#494]
https://www.m3conference.com/

---
for 
・MIMI
・ZARKO
・OLIVER

get receipts if possible

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
Elena is not here, so plz do this task today
(use business card

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I bought and printed the tickets, I couldn't get receipts since it was online payment, but I have received confirmation email for the payment. Should I give the tickets to Mimi, Zarko and Oliver today?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
plz give me tickets and also print the email of confirmation for payment (give it to accountant
