### ISSUE TITLE
registered trademark

### ISSUE THREAD

**Issue by writerity-kai** [timeriver/company-management#495]
Could you research about cost,if we apply registered trademark to five counties(france,spain,Germany,UK,Italy)?
And if you can,plz write down total cost simply.

※we will request①or ②company.
So,I want to compare two campanies.①and②
①Joanidis Law Firm and Patent Bureau company 
②Berin ltd, IP Agency

**Comment by writerity-kai** [comment]
@writerity-t-bojan 
@writerityelena 
If you can't understand,Please contact me anytime.

**Comment by writerity-kai** [comment]
@writerity-t-bojan 
thank you !
After updated it ,let me check.

**Comment by writerity-t-bojan** [comment]
@writerity-kai Updated spreadsheet.

https://docs.google.com/spreadsheets/d/1PIixGPimaqbDxLPx_SuZoCoBus9wkWL2LCjiaKQRbFA/edit#gid=0

**Comment by writerity-kai** [comment]
@writerity-t-bojan 
thank you.
I 'm done checking spread sheet.
