### ISSUE TITLE
Tax for profit (income tax) 2018

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#503]

**Comment by writerityelena** [comment]
1) 373 596 - we pay this tax at ones 

2) because this year, for the first time we have profit, not loss  (because accountant said last year you had loss around 41 000 MKD) Macedonia obliges our company to pay advanced payment every month in amount of 31 133 MKD - this money are going to be used for the next year income tax  i.e next year income tax 2020 will be deducted in amount of this monthly advanced payment during 2019

@writerity-watanabe 

[vrajterti virmani po zavrsna.pdf](https://github.com/timeriver/company-management/files/2971455/vrajterti.virmani.po.zavrsna.pdf)

**Comment by writerity-watanabe** [comment]
@writerityelena 
can you tell me more exactly?
I guess i dont understand that yet
