### ISSUE TITLE
Create account for Angelina

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#537]
gmail 
writerity.angelina@gmail.com

github
writerity-angelina

skype, chatwork...etc

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
tell me when all done

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe all done.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay thanks
