### ISSUE TITLE
Payment outsourcing fee to Toki at Ones account

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/company-management#55]
https://trello.com/c/9nCMx1Ns/350-%E6%99%82%E5%B7%9D%E7%B5%8C%E8%B2%BB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by writerityyuko** [comment]
@writerity-watanabe 

時川さんへの、外注費支払いの手続きの件です。
折田さんから、以下のメッセージをチャットワークで頂いています。
英訳等はこちらでやるのですか？？

> ワンズさんの登記の件ですが、
> 明日公証役場の近くまで行きますので
> 英語版ができれば持っていきますがいかがでしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
英訳をやってもらうようにワンズに伝えていますので
ライタリティではしないです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

１．登記簿取得
↓　　　　　　　（いまここ）
２．登記簿の英訳　
↓
３．公証役場等にてアポスティーユ取得
↓
４．日本語版と英語版の両方をマケドニアに送付
↓
５．マケドニアにて支払い手続き

という流れなので、今の感じだと、
折田さんからワンズのどなたかに連絡して英訳をしてもらってから、
再び折田さんに戻してもらい、公証役場に行ってもらうことになります。

今の時点でワンズに渡して、英訳とアポスティーユをとることをやってもらうのがスムーズな感じですが、難しいのでしょうか？
役割分担がよくわかりません。。。。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
流れはその認識でして
僕→ワンズ→折田さん→坂口さんになっているのだと思います。

＊ワンズの長田さんが忙しいため、おそらく長田さんから折田さんへ依頼した経緯

**Comment by writerityyuko** [comment]
@writerity-watanabe 

了解です。そうしましたら、折田さんには
ワンズに英訳をお願いして、それができたら公証役場行ってください、
とお願いしておきますね。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
了解です！
そういえば、エレナがカード作成していなくて何をしているのか分からないので
必ず、出社したら1日の作業（小さなタスクでも）を全てカード化して、常時１つのカードにDoingラベルが付くように随時更新するようにお願いします！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

今伝えましたー。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ワンズは時間がなくて英訳も全部折田さんにお願い、という感じだったようです。

ということで、折田さんのアイディアで、
豊田さんにアルバイトで登記簿の英訳を4000円くらいでしてもらい（費用はワンズに請求するとか）、
公印取得は折田さんにやっていただく、ということになりそうです。
現在豊田さんに打診中なので、まだ未確定ですが。

ご報告まで。

**Comment by writerityyuko** [comment]
[Ones To Watch_EN.pdf](https://github.com/timeriver/company-management/files/2675078/Ones.To.Watch_EN.pdf)

**Comment by writerityyuko** [comment]
[Ones To Watch. (1).pdf](https://github.com/timeriver/company-management/files/2675086/Ones.To.Watch.1.pdf)

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ワンズの登記簿の英訳が上がってきていますので、今確認をしています。（ご覧になる場合は、上の資料をお願いします）

以前のお話では「営業代行」という名目で請求書を出すということでしたが、
ワンズに請求するのであれば
請求名目がワンズの登記簿にある定款のどれかに合致していないと、こちらの経費処理時に突っつかれる可能性があると推察でき、
営業代行だと、ちょっと定款的に厳しいのかなと思っております。
代案としては、マーケティングのコンサルティング、として、定款の24に関係して見せてはどうかと思っていますが、いかがでしょうか？
あるいは、ほかにもこんなのどうか、というアイディアはありますでしょうか？

**Comment by writerityyuko** [comment]
http://houmukyoku.moj.go.jp/nagoya/static/s12.htm

**Comment by writerityyuko** [comment]
FMI

折田さんが公証役場でアポスティーユをとるためには、ワンズの長田さんの委任状が必要なため、折田さんから長田さんへ委任状を依頼済み。
その返事およびアポスティーユまち。
