### ISSUE TITLE
mandatory pension fund in MK

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#555]
what should i do with this?
![Transactions   KB First Portal](https://user-images.githubusercontent.com/36668646/55075317-f1948300-5092-11e9-94d6-156893ef0918.png)

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe The company is obligated to send you a report every year till the 31th March at latest. You don't have to do anything, this is merely for you to be informed about your account and pension fund. They sent you your username and pass, in case you want to check your account every once in a while.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
> your account and pension savings

when can I take this? or its just history and cannot take it?

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe This is just history about your pension savings status for the last 7 months. This savings will be eligible for you to take it after you fullfill the legal conditions for retirement :)

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
do you know the legal conditions for retirement?

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe According to article 18 from the Law on pension and disability insurance in MK, 
acquiring and establishing the rights for an Old-age pension:
- The insured person shall acquire the right to an old-age pension when he/she turns 64 years of age (men), that is, 62 years of age (women) and at least 15 years of pensionable service.
