### ISSUE TITLE
Invoice to KATSUMOK

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#556]
¥2,137,244

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Date of issue?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
today is okay

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe 
[Invoice, Writerity 004.pdf](https://github.com/timeriver/company-management/files/3013522/Invoice.Writerity.004.pdf)
