### ISSUE TITLE
Prepare Bonus for employee

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#59]

**Comment by writerityelena** [comment]
@writerity-watanabe we pay 24,162 as bonus ?

**Comment by writerity-watanabe** [comment]
@writerityelena 
already told you this
https://docs.google.com/spreadsheets/d/1gQVA8bIgdn8eShJfTBIamwzf275MLeAOUIa1MQlqVlY/edit?ts=5a539538#gid=395505017

**Comment by writerity-watanabe** [comment]
@writerityelena 
ex)
Dimitar will get "39,667"

and
need to update gross payment in the sheet

**Comment by writerityelena** [comment]
@writerity-watanabe 
I spoke with accountant and 
1) employee who has worked minimum 6 months must get recourse for vacation until end of December that is k-15 
2) recourse can be 9690 +10% tax or 14 318 (included tax)
3) this recourse (K-15) must be equal for everyone and its obligation 
4) so, if we pay more than 14 318 (like we discussed) we pay 10% personal tax and 10% income tax 
and must be same amount for everyone

**Comment by writerity-watanabe** [comment]
@writerityelena 
 okay then
we have to pay same amount as average salary

> 24,162 ?

**Comment by writerityelena** [comment]
@writerity-watanabe 
-24 162 is not obligationary amount 
-only 9 690 (minimum) is obligationary 
-everything that is more than 9 690 is up to you

**Comment by writerity-watanabe** [comment]
@writerityelena 
we pay 100% of average Macedonian salary of 2018 in the end of Dec, 2018

**Comment by writerityelena** [comment]
@writerity-watanabe 
100% of macedonian average salary as recourse for everyone  (should be)

**Comment by writerity-watanabe** [comment]
@writerityelena 
we pay 100% of average Macedonian salary of 2018 in the end of Dec, 2018
to Dimitar, Dimitri, Jovica, Kire

if average is 24,162, then each of 4 will get 24,162

**Comment by writerityelena** [comment]
@writerity-watanabe 
check this K-15 (yearly recourse and bonus) for employee if there is anything to be changed accountant can update 
[presmetka.pdf](https://github.com/timeriver/company-management/files/2675624/presmetka.pdf)

[vrajterti 13.12.2018.pdf](https://github.com/timeriver/company-management/files/2675625/vrajterti.13.12.2018.pdf)

**Comment by writerity-watanabe** [comment]
@writerityelena 
this is okay

**Comment by writerityelena** [comment]
@writerity-watanabe 
then we can pay this , next week or ?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay next week

**Comment by writerityelena** [comment]
@writerity-watanabe 

恐れ入ります !
