### ISSUE TITLE
Create paypal account for Writerity

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#6]
business account

---
use email "info@writerity.com"
and company credit card

**Comment by writerityelena** [comment]
@writerity-watanabe 
use email info@writerity.com
do you have pass for this emai;?

**Comment by writerity-watanabe** [comment]
@writerityelena 
will send in other tool (for security

**Comment by writerityelena** [comment]
@writerity-watanabe 
paypal pass: writerity2017
email: info@writerity.com

all set and done! :D
