### ISSUE TITLE
Order 20 business cards

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#60]

**Comment by writerity-watanabe** [comment]
@writerityelena 
only if I can get the card by 22nd Dec

**Comment by writerityelena** [comment]
@writerity-watanabe checking

**Comment by writerityelena** [comment]
@writerity-watanabe 
can be done on Dec 12 (Wed)  
100 cards = 861 MKD 
order?

**Comment by writerity-watanabe** [comment]
@writerityelena 
not 100

cannot buy only 20 or sth?

**Comment by writerityelena** [comment]
@writerity-watanabe 
no option for 20 
![image](https://user-images.githubusercontent.com/42862453/49724955-e72cb580-fc6a-11e8-9055-3941ca2f68f5.png)

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then 100
plz make sure the texture on front/back is same as mine

then you can make an order

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes already chose the same texture

**Comment by writerityelena** [comment]
@writerity-watanabe 
payment with business card ok?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks

**Comment by writerityelena** [comment]
@writerity-watanabe np
