### ISSUE TITLE
Prepare PC for new admin

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#75]

**Comment by writerityelena** [comment]
@writerityyuko ok ?

**Comment by writerityyuko** [comment]
@writerityelena 

ok for what? to make task?
if it is, of course ok. I put PC on the wallside desk already.

**Comment by writerityelena** [comment]
@writerityyuko tell me what i should prepare and when

**Comment by writerityyuko** [comment]
@writerityelena 

ok. 
just check whether the PC is working or not.
until Thursday
