### ISSUE TITLE
Jovica next contract

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#80]
800EUR - 1 year

**Comment by writerityelena** [comment]
@writerity-watanabe 
starting from when?

**Comment by writerity-watanabe** [comment]
@writerityelena 
16th Jan

**Comment by writerityelena** [comment]
@writerity-watanabe 

date of signing and when does he sign?

**Comment by writerity-watanabe** [comment]
@writerityelena 
today, tomorrow...if ready to sign anytime
