### ISSUE TITLE
ID from Verica and Co-Owner

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#81]

**Comment by writerity-watanabe** [comment]
@writerityelena
can you just wait contract for a while?

I need to talk with client about sth more.
and it will be after new year.

**Comment by writerityelena** [comment]
@writerity-watanabe sure np

**Comment by writerityelena** [comment]
@writerity-watanabe 
i received ID from Vedica and forwarded to Deni 
after they draft the contract Verica should check before signing

**Comment by writerity-watanabe** [comment]
@writerityelena 
before she check
I have to talk to client when we can sign
because now its designing step. and after we know the price for construction
i have to tell client and they decide

**Comment by writerityelena** [comment]
@writerity-watanabe 
yes i know, but she called me today and said that she cant approve anything to the architects until she signs

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay then we have to wait for a while
plz tell her we are sorry we cannot sign the contract yet 
(because we have to finish design and how much it cost for construction

**Comment by writerityelena** [comment]
@writerity-watanabe 
if its possible to be finished until end of this week suggestion 
because architects are also waiting and there are many holidays in January  - she said

**Comment by writerity-watanabe** [comment]
@writerityelena 
about design, probably can finish this week
after that they have to tell us price for construction and i will ask client to approve
