### ISSUE TITLE
Making revision of Designers

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#85]

**Comment by writerityelena** [comment]
@writerity-watanabe did Sac tell anything for this Oliver no.23
https://docs.google.com/spreadsheets/d/1YkPIO9s6wpP-Fugl0n-KbNjCqF9A-vt_grrH3FRveuU/edit#gid=370160821

**Comment by writerity-watanabe** [comment]
@writerityelena 
only this candidate you want to know?
i can ask client if there is someone else at the same time

**Comment by writerityelena** [comment]
@writerity-watanabe 
he is waiting out answer yet..and called 2 times for now

**Comment by writerity-watanabe** [comment]
@writerityelena 
anyone else?
only him? then i will ask client
