### ISSUE TITLE
Change password of all account for Bojan[intern]

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#91]
https://docs.google.com/spreadsheets/d/1XVIQj3HHkqpE_I81xdPfxB9ljgzfEHvH6dROEEfJwLs/edit#gid=379358399

**Comment by writerityelena** [comment]
@writerity-watanabe 
done 
pass: trdc321sh
except slack
pass: trdc321sh1

**Comment by writerity-watanabe** [comment]
@writerityelena 
oh thanks
I was about to do it
updated sheet, is this correct?
https://docs.google.com/spreadsheets/d/1XVIQj3HHkqpE_I81xdPfxB9ljgzfEHvH6dROEEfJwLs/edit#gid=379358399
