### ISSUE TITLE
Order cooler for Kire

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#97]
https://www.amc.com.mk/NOT-DOD-MSI-BALANCE-03-NOTEBOOK-156

**Comment by writerityelena** [comment]
@writerity-watanabe 
https://www.anhoch.com/product/44567/notebook-stand-gembird-up-to-1731x150mm-led-fan5-levels2xusb-black

this is ok to buy for Kire?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay
